
# General Stettings
permalink: /:categories/:year/:month/:day/:title

# Template Variables
title: 'Open Development Toolkit'
github: 'https://github.com/zararah/opendevtoolkit'
twitter: 'http://twitter.com/okfn'
contact: 'zara.rahman@okfn.org'

# Navigation
navigation:
- text: 'Beispiele'
  url: '/#beispiele'

